# This is a basic workflow to help you get started with Actions

name: Qt 5.15.2 on Linux

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Install prerequisite
        uses: ConorMacBride/install-package@v1
        with:
          apt: libdbus-glib-1-dev

      # Install Qt action
      - name: Install Qt
        uses: jurplel/install-qt-action@v3.0.0
        with:
          version: '5.15.2'
          host: 'linux'
          target: 'desktop'
        
      - name: qmake
        working-directory: ${{env.GITHUB_WORKSPACE}}
        run: qmake

      - name: make
        working-directory: ${{env.GITHUB_WORKSPACE}}
        run: make
